indent_stype = "Block"
comment_width = 100
format_code_in_doc_comments = true
import_granularity = "Crate"
normalize_comments = true
group_imports = "StdExternalCrate"
tab_spaces = 2
wrap_comments = true